environment:
  core_implementation: "open5gs"
  gnb_implementation: "srs"
  ric_implementation: "flexric"
  log_level: "INFO"
  log_dir: "logs"
  build_dir: "./repositories"
  docker_registry: "132.231.14.130:8080"
  tag_appendix: latest
  push_local_images: false


near_rt_ric:
  network:
    subnet: 10.0.2.0/24
    dbaas_ip: 10.0.2.12
    e2term_ip: 10.0.2.10
    e2mgr_ip: 10.0.2.11
    submgr_ip: 10.0.2.13
    appmgr_ip: 10.0.2.14
    rtmgr_sim_ip: 10.0.2.15
    xapp_runner_ip: 10.0.2.20
  vendors:
    - implementation: "oran_sc_ric" # Must correspond to RICImplementation(Enum) in model/ric_config.py
      repository: "https://github.com/srsran/oran-sc-ric.git"
      commit: "e44a7ce239b3c908e842163f1d57cbb4ba43fd0a"
      build_type: "docker"
      release: 'i'
    - implementation: "flexric"
      repository: "https://gitlab.eurecom.fr/mosaic5g/flexric.git"
      commit: "1f04cc558ebc8da9de6a620762bc02f5db4ecb4a"
      build_type: "docker"
      

5gc:
  network:
    5gc_ip: 10.53.1.2
    mongo_db_ip: 10.53.1.5
    subnet: 10.53.1.0/24
  vendors:
    - implementation: "open5gs" # must correspond to CoreImplementation(Enum) in model/core_config.py
      repository: "https://github.com/open5gs/open5gs.git"
      commit: "2b6369e9d997eb8eb158e3803e3ae4f4d207cd4d"
      build_type: "docker"
    - implementation: "open5gs_srs"
      repository: "https://github.com/srsran/srsRAN_Project.git"
      commit: "11c9bbabb69873752500d676f55e0034f6caa5c5"
      build_type: "docker"


ue:
  network:
    ip_range: 10.45.0.0/24
    gateway: 10.45.0.1
  ues:
    - ue:
        implementation: "srs_4g" # must correspond to UEImplementation(Enum) in model/ue_config.py
        repository: "https://github.com/srsran/srsRAN_4G.git"
        commit: "ec29b0c1ff79cebcbe66caa6d6b90778261c42b8"
        name: "ue1"
        build_type: "docker"
        ip_addr: 10.45.1.2
        srate: 11.52e6
        usim:
            mode: soft
            algo: milenage
            opc: 63BFA50EE6523365FF14C1F45F88737D
            key: 00112233445566778899aabbccddeeff
            imsi: 001010123456780
            imei: 353490069873319
        gateway:
            netns: ue1
            ip_devname: tun_srsue
            ip_netmask: 255.255.255.0

gnb:
  network:
    e2: 10.0.2.3
    ru_sdr: 10.45.1.1
    cu_cp: 10.53.1.3
  vendors:
    - implementation: "srs"
      repository: "https://github.com/srsran/srsRAN_Project.git"
      commit: "11c9bbabb69873752500d676f55e0034f6caa5c5"
      build_type: "docker"
      srate: 11.52e6
      tx_gain: 75
      rx_gain: 75
