version: "3.9"

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.45.0.0/16  # Internal network subnet

services:
    gnb:
        build: ./srsRAN_Project
        image: localhost:4000/gnb:selftag
        container_name: srsran_gnb
        privileged: true
        platform: linux/amd64
        networks:
            ran:
                ipv4_address: 10.53.1.3 # Pick an unused IP
            ric_network:
                ipv4_address: 10.0.2.3 # gNB IP on RIC network
            internal_net:
                ipv4_address: 10.45.1.1 # gNB IP on internal network
        user: root
        command: ["./build_docker/apps/gnb/gnb", "-c", "./configs/gnb_zmq.yaml"]
        volumes:
            - gnb_interface_log:/logs/gnb
        stdin_open: true
        tty: true
        restart: unless-stopped
        
volumes:
    gnb_interface_log:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/tmp/log/gnb' # replaced during patching