FROM ubuntu:latest

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libdw-dev \
    binutils-dev \
    libdwarf-dev \
    libelf-dev \
    pkg-config \
    libfftw3-dev \
    libyaml-cpp-dev \
    libmbedtls-dev \
    doxygen \
    libsctp-dev \
    libzmq3-dev \
    libzmq5 \
    git \
    && rm -rf /var/lib/apt/lists/*

# Set working directory and copy source
WORKDIR /app
COPY . .

# Build gNB
RUN rm -rf build_docker && mkdir build_docker && cd build_docker && cmake .. \
    -DENABLE_UHD=OFF \
    -DENABLE_ARMPL=OFF \
    -DENABLE_EXPORT=ON \
    -DENABLE_ZEROMQ=ON \
    -DCMAKE_CXX_FLAGS="-Wno-error=pessimizing-move" \
    && make -j"$(nproc)"

# Default command to start gNB
CMD ["./build/apps/gnb/gnb", "-c", "./configs/gnb_zmq.yaml"]
