version: "3.9"

networks:
  docker_ran:
    external: true
  oran-sc-ric_ric_network:
    external: true
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16  # Internal network subnet

services:
  gnb:
    build: ./srsRAN_Project
    container_name: srsran_gnb
    privileged: true
    platform: linux/amd64
    networks:
      docker_ran:
        ipv4_address: 10.53.1.3  # Pick an unused IP
      oran-sc-ric_ric_network:
        ipv4_address: 10.0.2.3   # gNB IP on RIC network
      internal_net:
        ipv4_address: 172.28.0.2   # gNB IP on internal network
    user: root
    volumes:
      - ./srsRAN_Project/configs:/app/configs
    command: ["./build/apps/gnb/gnb", "-c", "./configs/gnb_zmq.yaml"]
    stdin_open: true
    tty: true
    restart: unless-stopped

  ue:
    build: ./srsRAN_4G
    container_name: srsran_ue
    platform: linux/amd64
    networks:
      docker_ran:
        ipv4_address: 10.53.1.4   # Pick another unused IP
      oran-sc-ric_ric_network:
        ipv4_address: 10.0.2.5   # UE IP if needed on RIC network
      internal_net:
        ipv4_address: 172.28.0.3   # UE IP on internal network
    user: root
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./srsRAN_4G/configs:/app/configs
    #entrypoint: ["/app/entrypoint.sh"]
    stdin_open: true
    tty: true
    restart: unless-stopped
