parameters:
  core:
    service: 5gc
    address: 10.45.1.1
  user-equipments:
    ue1:
      service: ue1
      address: 10.45.1.2
    ue2:
      service: ue2
      address: 10.45.1.3
    ue3:
      service: ue3
      address: 10.45.1.4
  direction: DL
  workdir: ../repositories/
  granularity: 100ms
  loop: false
  use_nist: false
  nist_vm_ssh: root@132.231.14.134
  use_udp: false

# See doc/Trafficker.md for full documentation on all parameters and pattern types.

traffic:
  ue1:
    - periodic:
        size: 30kB
        interval: 1s
        duration: 10s

  ue2:
    - random:
        duration: 5s
        min_size: 0kB
        max_size: 10kB

  ue3:
    - loop:
        iterations: 3
        elements:
          - overlap:
              - periodic:
                  offset: 0ms
                  size: 30kB
                  interval: 100ms
                  duration: 5s
              - periodic:
                  offset: 1s
                  size: 15kB
                  interval: 400ms
                  duration: 4s
    - pause: 1s
    - overlap:
        - periodic:
            size: 20kB
            interval: 200ms
            duration: 5s
        - random:
            offset: 2s
            duration: 1s
            min_size: 0kB
            max_size: 40kB
    - pause: 1s
    - random:
        duration: 3s
        min_size: 10kB
        max_size: 50kB
    - pause: 1s
    - distribution:
        type: normal-distribution
        duration: 3s
        cumulative_size: 300kB
        mean: 0.5
        variance: 50
    - pause: 1s
    - overlap:
        - distribution:
            type: normal-distribution
            duration: 3s
            cumulative_size: 300kB
        - overlap:
            - offset: 500ms
            - distribution:
                type: uniform-distribution
                duration: 3s
                cumulative_size: 300kB
            - random:
                duration: 3s
                min_size: -2kB
                max_size: 2kB
    - pause: 1s
    - distribution:
        type: exponential-distribution
        duration: 3s
        cumulative_size: 300kB
    - pause: 1s
    - distribution:
        type: exponential-distribution
        duration: 3s
        cumulative_size: 300kB
        lambda: 0.2
        reverse: true
